// flow-typed signature: a613734b327c4796fb064a8946d28161
// flow-typed version: <<STUB>>/react-rouder-redux_v4.0.8/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-rouder-redux'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-rouder-redux' {
  declare module.exports: any;
}
